default: true
MD001: false  # Heading levels
MD004: false  # Unordered list style
MD007: false  # Unordered list indentation
MD009: false  # Trailing spaces
MD012: false  # Multiple consecutive blank lines
MD013: false  # Line length
MD022: false  # Blanks around headings
MD024: false  # Duplicate headings
MD026: false  # Trailing punctuation in headers
MD029: false  # Ordered list prefix
MD030: false  # Spaces after list markers
MD031: false  # Fenced code blocks blank lines
MD032: false  # Blanks around lists
MD033: false  # Inline HTML
MD034: false  # Bare URLs
MD036: false  # Emphasis used as heading
MD040: false  # Fenced code language (FIXES YOUR NEW ERROR)
MD041: false  # First line must be H1
MD042: false  # Empty Links
MD046: false  # Code block style
MD047: false  # Files should end with a single newline character
MD051: false  # Link fragments should be valid
MD052: false  # Reference links and images should use a label
MD053: false  # Link and image reference definitions should be needed
MD058: false  # Blanks around tables
MD060: false  # Table structure/style (FIXES YOUR NEW ERROR)
