#!/usr/bin/env python3
"""Generate the examples index from metadata in examples/*/README.md."""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
EXAMPLES_DIR = REPO_ROOT / "examples"
README_PATH = EXAMPLES_DIR / "README.md"
IGNORE_FILE = EXAMPLES_DIR / ".examples-ignore"

START_MARKER = "<!-- EXAMPLES:START -->"
END_MARKER = "<!-- EXAMPLES:END -->"
STACK_RE = re.compile(r"<!--\s*stack:\s*(.+?)\s*-->", re.IGNORECASE)
DESC_RE = re.compile(r"<!--\s*description:\s*(.+?)\s*-->", re.IGNORECASE)
MAX_DESCRIPTION_WORDS = 20

# One pre-metadata example is retained explicitly rather than hidden from the
# index. New examples must use the normal README metadata tags.
LEGACY_METADATA = {
    "lovable-sovereign-runtime": {
        "stack": "Lovable",
        "description": "Runtime enforcement package for Lovable Agent mode, database actions, deployments, and MCP integrations",
    },
}


def load_ignore_list() -> set[str]:
    if not IGNORE_FILE.exists():
        return set()
    return {
        line.strip()
        for line in IGNORE_FILE.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    }


def validate_and_read(folder: pathlib.Path, errors: list[str]) -> dict | None:
    readme = folder / "README.md"
    name = folder.name
    if not readme.exists():
        errors.append(f"{name}: no README.md found")
        return None

    text = readme.read_text(encoding="utf-8", errors="ignore")
    stack_match = STACK_RE.search(text)
    desc_match = DESC_RE.search(text)

    if not stack_match or not desc_match:
        legacy = LEGACY_METADATA.get(name)
        if legacy:
            return {"name": name, **legacy}
        if not stack_match:
            errors.append(f"{name}: missing <!-- stack: ... --> tag in README.md")
        if not desc_match:
            errors.append(f"{name}: missing <!-- description: ... --> tag in README.md")
        return None

    stack = stack_match.group(1).strip()
    description = desc_match.group(1).strip()
    if not stack:
        errors.append(f"{name}: stack tag is empty")
    if not description:
        errors.append(f"{name}: description tag is empty")
    if len(description.split()) > MAX_DESCRIPTION_WORDS:
        errors.append(
            f"{name}: description is {len(description.split())} words; "
            f"keep it under {MAX_DESCRIPTION_WORDS}"
        )
    if "\u2014" in description or "\u2013" in description or "--" in description:
        errors.append(f"{name}: description uses a disallowed dash sequence")
    if errors and any(error.startswith(f"{name}:") for error in errors):
        return None

    return {"name": name, "stack": stack, "description": description}


def build_table(rows: list[dict]) -> str:
    lines = ["| Example | Stack | What It Governs |", "|---|---|---|"]
    for row in sorted(rows, key=lambda item: item["name"]):
        link = f"[`{row['name']}/`](./{row['name']}/)"
        lines.append(f"| {link} | {row['stack']} | {row['description']} |")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    ignored = load_ignore_list()
    errors: list[str] = []
    rows: list[dict] = []

    for folder in sorted(EXAMPLES_DIR.iterdir()):
        if not folder.is_dir() or folder.name.startswith(".") or folder.name in ignored:
            continue
        metadata = validate_and_read(folder, errors)
        if metadata:
            rows.append(metadata)

    if errors:
        print("Examples table validation failed:", file=sys.stderr)
        for error in errors:
            print(f" - {error}", file=sys.stderr)
        return 1

    readme_text = README_PATH.read_text(encoding="utf-8")
    pattern = re.compile(
        re.escape(START_MARKER) + r".*?" + re.escape(END_MARKER),
        re.DOTALL,
    )
    if not pattern.search(readme_text):
        print("Examples index markers are missing from examples/README.md", file=sys.stderr)
        return 1

    table = build_table(rows)
    replacement = (
        f"{START_MARKER}\n"
        "<!-- This table is auto-generated by scripts/generate_examples_table.py. "
        "Do not hand-edit between these markers; edit each example's README.md instead. -->\n\n"
        f"{table}\n{END_MARKER}"
    )
    new_text = pattern.sub(replacement, readme_text)

    if new_text == readme_text:
        print("examples/README.md index already up to date")
        return 0
    if args.check:
        print("examples/README.md index is stale", file=sys.stderr)
        return 1

    README_PATH.write_text(new_text, encoding="utf-8")
    print(f"Updated examples index with {len(rows)} example(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
